### PR TITLE
Issue #32

### PR DESCRIPTION
**Pull request by RenatoSiqueira**
Rebuild HTML+CSS to minimize repeated itens.

### CODE REVIEW

**Comment by jaydson** [comment]
Hey @RenatoSiqueira ,
I'm testing your PR.
Let me clarify something, when I copy each item on the tool, what is copied is the full HTML.
Then I paste it on Mailchimp. It's there where I can see all the extra code.
Look at the screenshots below, we still have a lot of extra styles.

screenshot from 2018-10-12 12-22-44

screenshot from 2018-10-12 12-22-54

Perhaps is something related to the copy feature.

**Comment by RenatoSiqueira** [comment]
Done.
Check this PR now.
- Removed extras spaces on Outline
- Added PR38 by JulioGold manually
- Re-factoring some CSS and Codes

**Comment by jaydson** [comment]
Great job @RenatoSiqueira ! 🎉🎉🎉
I just checked and we still have some issues, but just in Chrome.
Look at the screenshots below.

## Google Chrome
screenshot from 2018-10-16 17-40-38

## Firefox
screenshot from 2018-10-16 17-40-57

I'll merge because it's exactly what we need!
I don't know what Chrome is doing, but it seems that it's an issue specific for it, so let's investigate later.

**Comment by jaydson** [comment]
I'll just ask something, can you please update your PR merging with the master? We had other PRs before and your PR is outdated and have some conflicts.

**Comment by RenatoSiqueira** [comment]
Merging Done!

About Chrome, maybe cache?
I´ll tested only in chrome kkkk
look:

image

**Comment by jaydson** [comment]
The problem is still there @RenatoSiqueira!
You're not going to reproduce it in dev tools.
The issue is when you copy the content, got it?
Try to copy and paste in an HTML editor, you'll have a lot of unnecessary code, which I think is just related to Chrome.

**Comment by RenatoSiqueira** [comment]
weird..
i´ll see more later.

**Pull request merged**
